### ISSUE TITLE
is there a "rows_affected()" or equivalent for dSQL queries?

### ISSUE THREAD

**Issue by kenirwin** [atk4/dsql#156]
Hi folks -- is there an `rows_affected()` method or something similar for dSQL queries? 

I have something like this
```
$this->q = $this->c->dsql();
$this->q->table('mytable')
 ->set('field1',$field1)
 ->set('field2',$field2)
 ->insert();
```

Is there a way to find out whether or not the query is successful? I'm imagining something like 
```
$this->q->rowsAffected()
```
but I dont see anything in the documentation to suggest that it exists. How do I check this?

Thanks!
Ken

**Comment by romaninsh** [comment]
No I don't think we have. But can this be implemented on all SQL vendors?

**Comment by DarkSide666** [comment]
Hi @kenirwin !

No we don't because as far as we checked there is no such method supported for all SQL engines :(

On the other hand, I don't see a reason to check this for `insert` statement because if insert will fail, then database engine (PDO for example) should throw exception. rows_affected could be more useful in update or delete statements, but you can still work around that requirement by first selecting count of records and only then update or delete.

**Comment by kenirwin** [comment]
Thanks @DarkSide666 -- I was looking for this feature for writing unit tests. Maybe I can test for a lack of exceptions instead. Do you have experience writing tests for the efficacy of insert statements with dSQL?

**Comment by DarkSide666** [comment]
How about:
```
    /**
     * @expectedException Exception
     */
    public function testException1()
    {
        // try to do something which should throw exception
    }
```

**Comment by kenirwin** [comment]
This phpunit addon supports testing for exceptions, which may do what I need
https://github.com/jchook/phpunit-assert-throws 

thanks

**Comment by DarkSide666** [comment]
Looks good, but it probably only supports PHPUnit 7.

**Comment by DarkSide666** [comment]
Closing.
