### ISSUE TITLE
Connection_Counter should not return iterator

### ISSUE THREAD

**Issue by mvorisek** [atk4/dsql#184]
See https://github.com/atk4/dsql/blob/f7bd5a13364755a44599bbabf369c180e10c28d4/src/Connection_Counter.php#L90

is it ok to refactor it, or is it intended?

**Comment by mvorisek** [comment]
@DarkSide666 ping

**Comment by DarkSide666** [comment]
This was done like that to be able to get resulting counters somehow.
Probably that's somewhere used, but should not be widely used. So I guess it could be refactored.
Thing is that if we refactor this method to return $this like other Counter classes do, then we will need additional method which would return this iterator. That way it will be almost BC - developer will need to just add additional method to actually get results.
`foreach($e->execute($sql)->getIterator())` instead of current `foreach($e->execute($sql))`

**Comment by mvorisek** [comment]
let it like it is, we can change once really an issue
