### ISSUE TITLE
Status/result of non-select Query

### ISSUE THREAD

**Issue by scottfriebel** [atk4/dsql#294]
Is there a way to determine whether a non-select query executed successfully since we don't have access to the return value of `$statement->execute();`? I can check `rowCount()` for a number of affected rows but an update query that doesn't affect any rows is still "successful" and that isn't reflected by the affect row count.

**Comment by DarkSide666** [comment]
@scottfriebel What you mean by unsuccessful execute? Can you give some example?
I think if you have wrong syntax or something in your statement, then it should throw exception and dsql should catch it and re-throw, so you probably should simply try/catch exceptions.

**Comment by scottfriebel** [comment]
`$statement->execute();` returns a true/false value but this value isn't passed from dsql back to the application and it doesn't appear that dsql even uses or looks at this value. However; if every unsuccessful query throws an exception, then that return value may not be relevant and I can assume that if an exception isn't thrown it was successful.

**Comment by DarkSide666** [comment]
I've never seen that PDO statement->execute() actually returns `false` instead of exception, but maybe there are cases. It would be great if you could come up with at least one example when PDO statement execute() returns `false` instead of exception. If there are such cases, then surely we should pass this return value back from ATK method too.
P.S. Updating 0 rows is also successful execution.

**Comment by scottfriebel** [comment]
From what I could find it appears that the only cases where `PDOStatement->execute` could possibly return `false` are memory allocation errors, which are probably unrecoverable regardless.
A previous library I was using used this return value and I was under the (apparently incorrect) assumption it was more relevant. Apparently it isn't; thanks for your time though!
